### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by Twil-7** [fluide1022/EnchantDance#3]
Thanks for your wonderful work, but it seems the files are missing when I run it.

Traceback (most recent call last):
  File "/mnt/code/EnchantDance-main/train.py", line 191, in <module>
    main()
  File "/mnt/code/EnchantDance-main/train.py", line 17, in main
    cfg = parse_args()
  File "/mnt/code/EnchantDance-main/enchant/config.py", line 161, in parse_args
    cfg_exp = OmegaConf.merge(cfg_base, OmegaConf.load(params.cfg))
  File "/root/miniconda3/lib/python3.10/site-packages/omegaconf/omegaconf.py", line 189, in load
    with io.open(os.path.abspath(file_), "r", encoding="utf-8") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/code/EnchantDance-main/configs/config.yaml'

**Comment by huzhongyyuan** [comment]
the same error

**Comment by fluide1022** [comment]
Fixed error. Pls check the new REAME

**Comment by webbrain-one** [comment]
Thanks for reporting this! I’ve opened PR [#5](https://github.com/fluide1022/EnchantDance/pull/5), which adds the missing config files, including `configs/config.yaml`, so the project can run without the `FileNotFoundError`.
